name: release

on:
  push:
    tags: "v*"

jobs:
  version-match:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install yq
        run: sudo snap install yq
      - name: Ensure version equality
        run: |
          IMAGE_TAG=$(yq e '.deployment.image' helm/values.yaml| cut -d ':' -f2)
          for COMMIT_TAG in $(git tag --points-at $(git rev-parse HEAD)); do
            if [[ "$IMAGE_TAG" == "$COMMIT_TAG" ]]; then
              exit 0
            fi
          done
          echo "Tag '$IMAGE_TAG' is not within tags of commit: $(git tag --points-at $(git rev-parse HEAD))"
          exit 1

  integration-test:
    runs-on: ubuntu-latest
    needs: [version-match]
    strategy:
      matrix:
        integration-test-script: [
          'integration-test.sh',
          'preconfig-integration-test.sh',
          'cosign-integration-test.sh',
          'namespaced-integration-test.sh',
          'deployment-integration-test.sh']
    services:
      alerting-endpoint:
        image: securesystemsengineering/alerting-endpoint
        ports:
          - 56243:56243
    steps:
      - uses: actions/checkout@v2
      - name: Install yq and bash
        run: |
          sudo snap install yq
          sudo apt update
          sudo apt install bash -y
      - name: Load Docker images
        run: |
          DOCKER_CONTENT_TRUST=1 docker pull $(yq e '.deployment.image' helm/values.yaml)
          DOCKER_CONTENT_TRUST=1 docker pull $(yq e '.deployment.helmHookImage' helm/values.yaml)
        shell: bash
      - uses: ./.github/actions/integration-test
        with:
          integration-test-script: ${{ matrix.integration-test-script }}

  publish_chart:
    runs-on: ubuntu-latest
    needs: [version-match, integration-test]
    steps:
    - name: Install helm
      run: |
        curl https://baltocdn.com/helm/signing.asc | sudo apt-key add -
        sudo apt-get install apt-transport-https --yes
        echo "deb https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
        sudo apt-get update
        sudo apt-get install helm git
    - name: Lint helm chart
      run: helm lint ./helm
    - name: Package and upload helm chart
      run: |
        git config user.name "versioning_user"
        git config user.email "connaisseur@securesystems.dev"
        git clone https://github.com/sse-secure-systems/connaisseur.git
        cd connaisseur
        helm package ./helm
        git checkout gh-pages
        mkdir -p charts
        mv connaisseur*.tgz ./charts
        cd charts
        helm repo index . --url https://sse-secure-systems.github.io/connaisseur/
        git add ./charts
        git commit -m "Publish helm chart"
        git push https://${{ secrets.GITHUB_TOKEN }}@github.com/sse-secure-systems/connaisseur.git
